language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update -q
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;


script:
    - composer install
    - vendor/bin/phpunit
    - vendor/bin/behat $BEHAT_TAGS

php:
    - 7.0
    - 5.6
    - 5.5
    - 5.4

env:
    - BEHAT_TAGS=""

matrix:
    include:
        - php: 7.0
          env: BEHAT_TAGS="--tags=@phpunit.phar"
